force-app/main/default/objects/Banner__mdt/Banner__mdt.object-meta.xml
<CustomObject>
    <label>Banner</label>
    <pluralLabel>Banners</pluralLabel>
</CustomObject>

force-app/main/default/objects/Banner__mdt/fields/Banner_Condition__c.field-meta.xml
<CustomField>
    <fullName>Banner_Condition__c</fullName>
    <inlineHelpText>Use includes rather than contains</inlineHelpText>
    <label>Banner Condition</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Banner__mdt/fields/Banner_Message__c.field-meta.xml
<CustomField>
    <fullName>Banner_Message__c</fullName>
    <label>Banner Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Banner__mdt/fields/Banner_Setting__c.field-meta.xml
<CustomField>
    <fullName>Banner_Setting__c</fullName>
    <label>Banner Setting</label>
    <referenceTo>Banner_Setting__mdt</referenceTo>
    <relationshipLabel>Banners</relationshipLabel>
    <relationshipName>Banners</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Banner__mdt/fields/Banner_Type__c.field-meta.xml
<CustomField>
    <fullName>Banner_Type__c</fullName>
    <label>Banner Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
                <default>true</default>
                <label>Error</label>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Banner_Setting__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <label>Object API Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Banner_Setting__mdt/fields/Query_Fields__c.field-meta.xml
<CustomField>
    <fullName>Query_Fields__c</fullName>
    <label>Query Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/BannerController.cls
public with sharing class BannerController {

    @AuraEnabled(cacheable = true)
    public static PageBnrWrapper generateBannerDetails(String recordId) {

        PageBnrWrapper newPageBanner = new PageBnrWrapper();
        String queryFields;
        String whereClause = 'ID = :recordId';
        String objtype = String.valueof(Id.valueOf(recordId).getSobjectType());
        List<banner__mdt> banners = new List<banner__mdt>();

        for(Banner_Setting__mdt bs : getBannerDetails(objtype))
        {
            banners = (list<banner__mdt>)bs.Banners__r;
            queryFields = generateQuery(bs.Query_Fields__c , objtype , whereClause);
        }

        if(queryFields <> null && banners.size() > 0)
        {
            newPageBanner.recordData = database.query(queryFields);
            //system.debug('banner*****' + JSON.serialize(newPageBanner.recordData) );
            List<PageBnrWrapperElement> bannerList = new List<PageBnrWrapperElement>();
            for(banner__mdt banner : banners)
            {
                bannerList.add(generateWrapperElement(banner));
            }
            newPageBanner.bannerList = bannerList;
            //system.debug(newPageBanner);
            return newPageBanner;               
        }
        return null;
    } 
    
    private static String generateQuery(String fields, String objName , String whereClause)
    {
        String escapedFields = String.escapeSingleQuotes(fields);
        return 'SELECT ' + escapedFields + ' FROM ' + objName + ' WHERE ' + whereClause + ' LIMIT 1 ' ;
    }

    private static List<Banner_Setting__mdt> getBannerDetails(String objName)
    {
        List<Banner_Setting__mdt> bannerSettings = new List<Banner_Setting__mdt>();
        bannerSettings = [select id,Query_Fields__c,(select id,DeveloperName,Active__c,Banner_Condition__c,Banner_Message__c,Banner_Type__c,Help_Text__c from Banners__r where Active__c = true) from Banner_Setting__mdt where Active__c = true and Object_API_Name__c = :objName limit 1];
        return bannerSettings;
    }

    public static PageBnrWrapperElement generateWrapperElement(banner__mdt banner)
    {
        PageBnrWrapperElement pwElement = new PageBnrWrapperElement();
            pwElement.id = banner.DeveloperName;
            pwElement.msg =  banner.Banner_Message__c;
            pwElement.helptext = banner.Help_Text__c ;
            pwElement.condition = banner.Banner_Condition__c?.replace('.','?.');
            pwElement.type = banner.Banner_Type__c;
        return pwElement;
    }

    public with sharing class PageBnrWrapper {
        @AuraEnabled public sObject recordData;
        @AuraEnabled public List<PageBnrWrapperElement> bannerList;
    }
    public with sharing class PageBnrWrapperElement {
        @AuraEnabled public string id;
        @AuraEnabled public string msg;
        @AuraEnabled public string helptext;
        @AuraEnabled public string condition;
        @AuraEnabled public string type;
    }
}